package co.model.pojos;
// Generated 9/09/2018 07:52:03 PM by Hibernate Tools 4.3.1



/**
 * TblUsuario generated by hbm2java
 */
public class TblUsuario  implements java.io.Serializable {


     private int id;
     private String nombre;

    public TblUsuario() {
    }

    public TblUsuario(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
    
    
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


